name: "Build & Tests"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/api-user?serverVersion=5.7
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Check runtime version
        run: php -v && composer --version
      - name: Install dependencies
        run: composer install -o
      - name: Start Mysql
        run: sudo systemctl start mysql
      - name: Create database
        run: bin/console doctrine:database:create --env test
      - name: Create database schema
        run: bin/console doctrine:schema:create --env test
      - name: Run functional tests
        run: bin/phpunit